server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: store.manager
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}
      database: ${MONGO_DB}
logging:
  level:
    org:
      springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG